### PR TITLE
meson: Fix anthy-unicode.conf search path in mkdepgraph

### LINKED ISSUE #14: Anthy dictionaries are not built correctly with Meson
From https://bugzilla.redhat.com/show_bug.cgi?id=2436172

Since Fedora-Rawhide-20260128.n.0 , the openQA Japanese input test is failing.

In the test, we add Japanese (Anthy) input source and enable it. Then we go to a console and type 'yama'. This correctly shows やま ('yama' in hiragana). Next we press space, and expect it to produce 山 (the most likely kanji character). That's what it did until Fedora-Rawhide-20260127.n.0 . However, now it produces や真 , which is pretty useless.

I can reproduce this locally on my F44 Silverblue system. If I hit space again to get the menu, it seems to offer me completions for *each character alone*, not for the whole string - like it's offering me potential kanji for 'や' alone, not the whole word 'やま', and if I hit the right arrow key it scrolls over to 'ま' and starts offering me completions for that character alone.

This is a general issue, it doesn't just affect this one test word...it's the same with e.g. ぼく (completion gives 墓句 not 僕) and anything else I've tried.

In Fedora-Rawhide-20260128.n.0 I see that ibus-anthy went from 1.5.17-9.fc44 to 1.5.17-10.fc44 and anthy-unicode went from 1.0.0.20240502-13.fc44 to 1.0.0.20260127-1.fc44 ; I guess one of those is likely to be the cause, though ibus-anthy was just a rebuild...

### PR DESCRIPTION
**Pull request by oreo639**
Resolves issue where a blank anthy.dep is generated when using the meson build system. This is due to the anthy-unicode.conf path not being adjusted between meson and autotools.

BUG=#14

### CODE REVIEW

File: depgraph/mkdepgraph.c [hunk 1]
```diff
@@ -43,6 +43,10 @@
 #define SRCDIR "."
 #endif
 
+#ifndef CONFDIR
+#define CONFDIR ".."
```
Comment (fujiwarat) [inline depgraph/mkdepgraph.c]: Probably I'd think to swap the lines of SRCDIR and ones of CONFDIR for the alphabet order.

**Review by fujiwarat — COMMENTED** [review]
Thank you for the patch. I'm a bit surprised by your quick investigation.

Probably I think the top_builddir is not needed at the moment.
I'd like to think `s/-DCONFDIR="@0@"'.format((meson.project_build_root()))/-DBLDDIR="@0@"'.format(meson.current_build_dir())/` and
`s|CONFDIR "/anthy-unicode.conf"|BLDDIR "/../anthy-unicode.conf"|`.

**Comment by fujiwarat** [comment]
Thank you. LGTM.
Will make the new tag soon.
